# Generated by Django 5.1.4 on 2026-05-27 02:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('expected_farrowing_date', models.DateField(verbose_name='Fecha probable de parto')),
                ('status', models.CharField(choices=[('confirmed', 'Confirmada'), ('suspected', 'Sospecha'), ('not_pregnant', 'No gestante'), ('aborted', 'Abortada')], default='suspected', max_length=20, verbose_name='Estado')),
                ('confirmed_date', models.DateField(blank=True, null=True, verbose_name='Fecha de confirmación')),
                ('ultrasound_result', models.BooleanField(null=True, verbose_name='Resultado de ecografía')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sow', models.ForeignKey(limit_choices_to={'sex': 'female'}, on_delete=django.db.models.deletion.CASCADE, related_name='gestations', to='animals.pig', verbose_name='Cerda')),
            ],
            options={
                'verbose_name': 'Gestación',
                'verbose_name_plural': 'Gestiones',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Farrowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farrowing_date', models.DateField(verbose_name='Fecha de parto')),
                ('piglets_alive', models.PositiveIntegerField(default=0, verbose_name='Lechones vivos')),
                ('piglets_stillborn', models.PositiveIntegerField(default=0, verbose_name='Lechones nacidos muertos')),
                ('piglets_mummies', models.PositiveIntegerField(default=0, verbose_name='Momificados')),
                ('piglets_total', models.PositiveIntegerField(editable=False, verbose_name='Total lechones')),
                ('assisted', models.BooleanField(default=False, verbose_name='Parto asistido')),
                ('attended_by', models.CharField(blank=True, max_length=100, verbose_name='Atendido por')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sow', models.ForeignKey(limit_choices_to={'sex': 'female'}, on_delete=django.db.models.deletion.CASCADE, related_name='farrowings', to='animals.pig', verbose_name='Cerda')),
                ('gestation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farrowings', to='reproduction.gestation', verbose_name='Gestación')),
            ],
            options={
                'verbose_name': 'Parto',
                'verbose_name_plural': 'Partos',
                'ordering': ['-farrowing_date'],
            },
        ),
        migrations.CreateModel(
            name='HeatDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heat_date', models.DateField(verbose_name='Fecha de celo')),
                ('detected_by', models.CharField(blank=True, max_length=100, verbose_name='Detectado por')),
                ('symptoms', models.TextField(blank=True, verbose_name='Síntomas')),
                ('intensity', models.CharField(choices=[('low', 'Bajo'), ('medium', 'Medio'), ('high', 'Alto')], default='medium', max_length=20, verbose_name='Intensidad')),
                ('is_mated', models.BooleanField(default=False, verbose_name='¿Fue montada?')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sow', models.ForeignKey(limit_choices_to={'category': 'sow', 'sex': 'female'}, on_delete=django.db.models.deletion.CASCADE, related_name='heat_events', to='animals.pig', verbose_name='Cerda')),
            ],
            options={
                'verbose_name': 'Detección de celo',
                'verbose_name_plural': 'Detecciones de celo',
                'ordering': ['-heat_date'],
            },
        ),
        migrations.CreateModel(
            name='Mating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mating_type', models.CharField(choices=[('natural', 'Monta natural'), ('artificial', 'Inseminación artificial')], default='natural', max_length=20, verbose_name='Tipo de monta')),
                ('mating_date', models.DateField(verbose_name='Fecha de monta')),
                ('time_of_day', models.CharField(blank=True, choices=[('morning', 'Mañana'), ('afternoon', 'Tarde')], max_length=10, verbose_name='Horario')),
                ('semen_source', models.CharField(blank=True, max_length=100, verbose_name='Fuente de semen')),
                ('technician', models.CharField(blank=True, max_length=100, verbose_name='Técnico')),
                ('is_successful', models.BooleanField(null=True, verbose_name='¿Exitosa?')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('boar', models.ForeignKey(blank=True, limit_choices_to={'sex': 'male'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mating_boar', to='animals.pig', verbose_name='Verraco')),
                ('sow', models.ForeignKey(limit_choices_to={'sex': 'female'}, on_delete=django.db.models.deletion.CASCADE, related_name='matings', to='animals.pig', verbose_name='Cerda')),
            ],
            options={
                'verbose_name': 'Monta',
                'verbose_name_plural': 'Montas',
                'ordering': ['-mating_date'],
            },
        ),
        migrations.AddField(
            model_name='gestation',
            name='mating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gestations', to='reproduction.mating', verbose_name='Monta'),
        ),
        migrations.CreateModel(
            name='PigletBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('sex', models.CharField(choices=[('male', 'Macho'), ('female', 'Hembra'), ('mixed', 'Mixto')], max_length=10, verbose_name='Sexo')),
                ('birth_weight_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Peso promedio (kg)')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('farrowing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piglet_batches', to='reproduction.farrowing', verbose_name='Parto')),
            ],
            options={
                'verbose_name': 'Lote de lechones',
                'verbose_name_plural': 'Lotes de lechones',
            },
        ),
        migrations.CreateModel(
            name='Weaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weaning_date', models.DateField(verbose_name='Fecha de destete')),
                ('piglets_weaned', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Lechones destetados')),
                ('avg_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Peso promedio (kg)')),
                ('age_days', models.PositiveIntegerField(editable=False, verbose_name='Edad al destete (días)')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farrowing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weanings', to='reproduction.farrowing', verbose_name='Parto')),
                ('sow', models.ForeignKey(limit_choices_to={'sex': 'female'}, on_delete=django.db.models.deletion.CASCADE, related_name='weanings', to='animals.pig', verbose_name='Cerda')),
            ],
            options={
                'verbose_name': 'Destete',
                'verbose_name_plural': 'Destetes',
                'ordering': ['-weaning_date'],
            },
        ),
    ]
