# Generated by Django 5.1.4 on 2026-06-25 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reproduction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestation',
            name='expected_farrowing_date',
            field=models.DateField(editable=False, verbose_name='Fecha probable de parto'),
        ),
    ]
