# Generated by Django 5.1.4 on 2026-05-27 02:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='Proveedor')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo unitario')),
                ('unit_measure', models.CharField(default='kg', max_length=50, verbose_name='Unidad de medida')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de alimento',
                'verbose_name_plural': 'Tipos de alimento',
            },
        ),
        migrations.CreateModel(
            name='FeedInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad en stock')),
                ('entry_date', models.DateField(verbose_name='Fecha de ingreso')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento')),
                ('batch_number', models.CharField(blank=True, max_length=100, verbose_name='Lote')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feed_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='feeding.feedtype', verbose_name='Alimento')),
            ],
            options={
                'verbose_name': 'Inventario de alimento',
                'verbose_name_plural': 'Inventarios de alimento',
                'ordering': ['-entry_date'],
            },
        ),
        migrations.CreateModel(
            name='FeedConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='animals.location', verbose_name='Ubicación')),
                ('pig', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed_consumptions', to='animals.pig', verbose_name='Cerdo')),
                ('feed_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeding.feedtype', verbose_name='Alimento')),
            ],
            options={
                'verbose_name': 'Consumo de alimento',
                'verbose_name_plural': 'Consumos de alimento',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de dieta')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('daily_amount_per_pig', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad diaria por cerdo')),
                ('min_age_days', models.PositiveIntegerField(default=0, verbose_name='Edad mínima (días)')),
                ('max_age_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad máxima (días)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('feed_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeding.feedtype', verbose_name='Alimento')),
            ],
            options={
                'verbose_name': 'Dieta',
                'verbose_name_plural': 'Dietas',
            },
        ),
    ]
