# Generated by Django 5.1.4 on 2026-06-25 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeding', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedconsumption',
            name='pig',
        ),
    ]
