# Generated by Django 5.1.4 on 2026-06-25 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeding', '0002_remove_pig_from_feed_consumption'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='pig_category',
            field=models.CharField(choices=[('sow', 'Cerda Madre'), ('boar', 'Verraco'), ('piglet', 'Lechón'), ('grower', 'Cerdo Engorde'), ('replacement', 'Reemplazo')], default='sow', max_length=20, verbose_name='Categoría de cerdo'),
        ),
        migrations.AlterUniqueTogether(
            name='diet',
            unique_together={('feed_type', 'pig_category')},
        ),
    ]
