# Generated by Django 5.1.4 on 2026-06-25 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeding', '0003_add_pig_category_to_diet'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='diet',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='diet',
            name='sow_status',
            field=models.CharField(blank=True, choices=[('empty', 'Vacía'), ('gestating', 'Gestante'), ('lactating', 'Lactante')], max_length=20, null=True, verbose_name='Estado reproductivo (solo cerdas)'),
        ),
        migrations.AlterField(
            model_name='diet',
            name='pig_category',
            field=models.CharField(choices=[('sow', 'Cerda Madre'), ('boar', 'Verraco'), ('piglet', 'Lechón'), ('grower', 'Cerdo Engorde'), ('replacement', 'Reemplazo')], max_length=20, verbose_name='Categoría de cerdo'),
        ),
        migrations.AlterUniqueTogether(
            name='diet',
            unique_together={('feed_type', 'pig_category', 'sow_status')},
        ),
    ]
