# Generated by Django 5.1.4 on 2026-05-27 02:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GrowOutBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del lote')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('pigs_count', models.PositiveIntegerField(verbose_name='Cantidad de cerdos')),
                ('avg_start_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Peso inicial promedio')),
                ('target_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Peso objetivo')),
                ('status', models.CharField(choices=[('growing', 'En engorde'), ('finished', 'Finalizado'), ('sold', 'Vendido')], default='growing', max_length=20, verbose_name='Estado')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='animals.location', verbose_name='Ubicación')),
            ],
            options={
                'verbose_name': 'Lote de engorde',
                'verbose_name_plural': 'Lotes de engorde',
            },
        ),
        migrations.CreateModel(
            name='GrowOutPig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Peso de entrada')),
                ('exit_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Peso de salida')),
                ('exit_date', models.DateField(blank=True, null=True, verbose_name='Fecha de salida')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pigs', to='sales.growoutbatch', verbose_name='Lote')),
                ('pig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grow_out_batches', to='animals.pig', verbose_name='Cerdo')),
            ],
            options={
                'verbose_name': 'Cerdo en engorde',
                'verbose_name_plural': 'Cerdos en engorde',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField(verbose_name='Fecha de venta')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='Estado')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto total')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Método de pago')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='sales.customer', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-sale_date'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Descripción')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio unitario')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Peso (kg)')),
                ('line_total', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Total')),
                ('pig', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='animals.pig', verbose_name='Cerdo')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Item de venta',
                'verbose_name_plural': 'Items de venta',
            },
        ),
    ]
