# Generated by Django 5.1.4 on 2026-06-25 04:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300, verbose_name='Descripción')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('category', models.CharField(choices=[('worker', 'Pago de trabajador'), ('feed', 'Alimento'), ('health', 'Salud'), ('services', 'Servicios'), ('maintenance', 'Mantenimiento'), ('other', 'Otros')], default='other', max_length=20, verbose_name='Categoría')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WorkerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=200, verbose_name='Nombre del trabajador')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto')),
                ('payment_date', models.DateField(verbose_name='Fecha de pago')),
                ('frequency', models.CharField(choices=[('weekly', 'Semanal'), ('biweekly', 'Quincenal'), ('monthly', 'Mensual')], max_length=20, verbose_name='Frecuencia')),
                ('period_start', models.DateField(verbose_name='Inicio del período')),
                ('period_end', models.DateField(verbose_name='Fin del período')),
                ('category', models.CharField(choices=[('worker', 'Pago de trabajador'), ('feed', 'Alimento'), ('health', 'Salud'), ('services', 'Servicios'), ('maintenance', 'Mantenimiento'), ('other', 'Otros')], default='worker', max_length=20, verbose_name='Categoría')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pago a trabajador',
                'verbose_name_plural': 'Pagos a trabajadores',
                'ordering': ['-payment_date'],
            },
        ),
    ]
