# Generated by Django 5.1.4 on 2026-05-27 02:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Raza')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Raza',
                'verbose_name_plural': 'Razas',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('capacity', models.PositiveIntegerField(default=0, verbose_name='Capacidad')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
            },
        ),
        migrations.CreateModel(
            name='Pig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ear_tag', models.CharField(max_length=50, unique=True, verbose_name='Arete/ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Nombre')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('sex', models.CharField(choices=[('male', 'Macho'), ('female', 'Hembra')], max_length=10, verbose_name='Sexo')),
                ('category', models.CharField(choices=[('sow', 'Cerda Madre'), ('boar', 'Verraco'), ('piglet', 'Lechón'), ('grower', 'Cerdo Engorde'), ('replacement', 'Reemplazo')], default='sow', max_length=20, verbose_name='Categoría')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('sold', 'Vendido'), ('dead', 'Muerto'), ('transferred', 'Transferido')], default='active', max_length=20, verbose_name='Estado')),
                ('entry_date', models.DateField(auto_now_add=True, verbose_name='Fecha de ingreso')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('breed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='animals.breed', verbose_name='Raza')),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring_father', to='animals.pig', verbose_name='Padre')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='animals.location', verbose_name='Ubicación')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring_mother', to='animals.pig', verbose_name='Madre')),
            ],
            options={
                'verbose_name': 'Cerdo',
                'verbose_name_plural': 'Cerdos',
            },
        ),
        migrations.CreateModel(
            name='WeightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Peso (kg)')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='animals.pig', verbose_name='Cerdo')),
            ],
            options={
                'verbose_name': 'Registro de peso',
                'verbose_name_plural': 'Registros de peso',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='pig',
            index=models.Index(fields=['ear_tag'], name='animals_pig_ear_tag_16a037_idx'),
        ),
        migrations.AddIndex(
            model_name='pig',
            index=models.Index(fields=['status'], name='animals_pig_status_380259_idx'),
        ),
        migrations.AddIndex(
            model_name='pig',
            index=models.Index(fields=['category'], name='animals_pig_categor_2a3b7f_idx'),
        ),
    ]
