# Generated by Django 5.1.4 on 2026-06-25 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pig',
            name='sow_status',
            field=models.CharField(blank=True, choices=[('empty', 'Vacía'), ('gestating', 'Gestante'), ('lactating', 'Lactante')], max_length=20, null=True, verbose_name='Estado reproductivo'),
        ),
    ]
