# Generated by Django 5.1.4 on 2026-05-27 02:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccinationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del esquema')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Esquema de vacunación',
                'verbose_name_plural': 'Esquemas de vacunación',
            },
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('laboratory', models.CharField(blank=True, max_length=200, verbose_name='Laboratorio')),
                ('lot_number', models.CharField(blank=True, max_length=100, verbose_name='Lote')),
                ('presentation', models.CharField(blank=True, max_length=100, verbose_name='Presentación')),
                ('days_to_immunity', models.PositiveIntegerField(default=0, verbose_name='Días hasta inmunidad')),
                ('duration_days', models.PositiveIntegerField(default=180, verbose_name='Duración (días)')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Vacuna',
                'verbose_name_plural': 'Vacunas',
            },
        ),
        migrations.CreateModel(
            name='MortalityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('death_date', models.DateField(verbose_name='Fecha de muerte')),
                ('cause', models.CharField(choices=[('disease', 'Enfermedad'), ('crushed', 'Aplastamiento'), ('diarrhea', 'Diarrea'), ('respiratory', 'Problema respiratorio'), ('congenital', 'Malformación congénita'), ('trauma', 'Traumatismo'), ('unknown', 'Causa desconocida'), ('other', 'Otro')], default='unknown', max_length=20, verbose_name='Causa')),
                ('age_days', models.PositiveIntegerField(editable=False, verbose_name='Edad (días)')),
                ('necropsy_performed', models.BooleanField(default=False, verbose_name='¿Necropsia realizada?')),
                ('necropsy_results', models.TextField(blank=True, verbose_name='Resultados de necropsia')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortality_records', to='animals.pig', verbose_name='Cerdo')),
            ],
            options={
                'verbose_name': 'Registro de mortalidad',
                'verbose_name_plural': 'Registros de mortalidad',
                'ordering': ['-death_date'],
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_type', models.CharField(choices=[('antibiotic', 'Antibiótico'), ('antiinflammatory', 'Antiinflamatorio'), ('antiparasitic', 'Antiparasitario'), ('vitamin', 'Vitamina'), ('other', 'Otro')], max_length=20, verbose_name='Tipo')),
                ('medication', models.CharField(max_length=200, verbose_name='Medicamento')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('dosage', models.CharField(blank=True, max_length=100, verbose_name='Dosis')),
                ('applied_by', models.CharField(blank=True, max_length=100, verbose_name='Aplicado por')),
                ('diagnosis', models.TextField(blank=True, verbose_name='Diagnóstico')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='animals.pig', verbose_name='Cerdo')),
            ],
            options={
                'verbose_name': 'Tratamiento',
                'verbose_name_plural': 'Tratamientos',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='VaccinationScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose_number', models.PositiveIntegerField(default=1, verbose_name='Número de dosis')),
                ('apply_at_age_days', models.PositiveIntegerField(verbose_name='Aplicar a los (días)')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='health.vaccinationschedule', verbose_name='Esquema')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.vaccine', verbose_name='Vacuna')),
            ],
            options={
                'verbose_name': 'Item del esquema',
                'verbose_name_plural': 'Items del esquema',
                'ordering': ['apply_at_age_days', 'dose_number'],
            },
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateField(verbose_name='Fecha de aplicación')),
                ('dose_ml', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Dosis (ml)')),
                ('applied_by', models.CharField(blank=True, max_length=100, verbose_name='Aplicado por')),
                ('batch_number', models.CharField(blank=True, max_length=100, verbose_name='Lote de la vacuna')),
                ('next_due_date', models.DateField(blank=True, null=True, verbose_name='Próxima dosis')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='animals.pig', verbose_name='Cerdo')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.vaccine', verbose_name='Vacuna')),
            ],
            options={
                'verbose_name': 'Registro de vacunación',
                'verbose_name_plural': 'Registros de vacunación',
                'ordering': ['-application_date'],
            },
        ),
    ]
